#!/bin/bash

runAndReportIfError() {
  "${@:2}" > "${1}"
  EXIT_CODE=$?
  if [ $EXIT_CODE -ne 0 ]; then
    cat >&2 "${1}"
    return $EXIT_CODE
  fi
}
export -f runAndReportIfError

REPORT_DIR="build/pre-commit"
rm -rf $REPORT_DIR || true
mkdir -p ${REPORT_DIR}

parallel --halt now,done=1 ::: "runAndReportIfError ${REPORT_DIR}/ktlint.log ./.scripts/check_ktlint.sh"
parallel --halt now,done=1 ::: "./gradlew clean build"
