#!/bin/bash
set -e

REPORT_DIR="build/pre-commit"
rm -rf $REPORT_DIR || true
mkdir -p ${REPORT_DIR}

BUILD_TASK_FILE=${REPORT_DIR}/build.log
./gradlew build >> $BUILD_TASK_FILE || (cat $BUILD_TASK_FILE && exit 1) &
KTLINT_TASK_FILE=${REPORT_DIR}/ktlint.log
./.scripts/check_ktlint.sh >> $KTLINT_TASK_FILE || (cat $KTLINT_TASK_FILE && exit 1)

wait
